### ISSUE TITLE
Необязательно по 4, в зависимости от задания

### ISSUE THREAD

**Issue by deevroman** [RedGry/ITMO-Digital-ulture#4]
https://github.com/RedGry/ITMO-DigitalCulture/blob/9363bb0bb0514a219f66a0ff938eade298499340/%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F%20%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C.py#L14

**Comment by RedGry** [comment]
Умеем читать русские буквы? ПРИМЕР
